# Generated by Django 5.0.7 on 2024-07-17 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xuitter", "0003_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Posts",
        ),
    ]
