# Generated by Django 5.0.7 on 2024-07-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xuitter", "0005_rename_posts_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
