# Generated by Django 5.0.7 on 2024-07-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xuitter", "0008_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
